### ISSUE TITLE
Error when using cleft.threshold in flywire_partners_summary

### ISSUE THREAD

**Issue by mmc46** [natverse/fafbseg#118] opened 2021-04-23 16:29 UTC
The first is the example in the docs.

``` r
library(fafbseg)
#> Loading required package: nat
#> Loading required package: rgl
#> Registered S3 method overwritten by 'nat':
#>   method             from
#>   as.mesh3d.ashape3d rgl
#> 
#> Attaching package: 'nat'
#> The following object is masked from 'package:rgl':
#> 
#>     wire3d
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, union
#> Run dr_fafbseg() for a status report on your installation

pout = flywire_partner_summary("720575940621039145", partners='out')
#> Fetching supervoxel ids for id: 720575940621039145
#> Finding synapses for supervoxels
#> Fetching root ids
pout30 = flywire_partner_summary("720575940621039145", partners='out', cleft.threshold = 30)
#> Error in if (details) {: argument is not interpretable as logical
```

**Comment by jefferis** [comment] 2021-04-23 22:13
duplicate of #118, closed by 1e5911a

**Closed by jefferis** 2021-04-23 22:13 UTC
